# -*- coding: utf-8 -*-
"""SQL_Query_Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NEbZBu8754qkwBJw0vuCjLCD2mlHdRgV
"""

!pip install -q gradio transformers torch reportlab

import re
import sqlite3
import gradio as gr
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch
from datetime import datetime

schema = {
    "users": ["id", "name", "email", "signup_date", "age", "country", "status"],
    "orders": ["id", "user_id", "product_name", "amount", "order_date", "status"],
    "products": ["id", "name", "price", "category", "stock"],
    "transactions": ["id", "user_id", "amount", "date", "type"]
}

dangerous_keywords = ["DROP", "DELETE", "ALTER", "TRUNCATE",
                      "INSERT", "UPDATE", "EXEC", "EXECUTE"]

def is_safe(user_input):
    upper_input = user_input.upper()

    for word in dangerous_keywords:
        if word in upper_input:
            return False

    if ";" in user_input or "--" in user_input:
        return False

    return True

def get_table_name(text):
    text = text.lower()

    if any(word in text for word in ["user", "customer", "account"]):
        return "users"
    elif any(word in text for word in ["order", "purchase"]):
        return "orders"
    elif any(word in text for word in ["product", "item"]):
        return "products"
    elif any(word in text for word in ["transaction", "payment"]):
        return "transactions"

    return None

def extract_conditions(text):
    text = text.lower()
    conditions = []

    # Last month condition
    if "last month" in text:
        conditions.append("DATE(signup_date) >= DATE('now','-1 month')")

    # Last week condition
    if "last week" in text:
        conditions.append("DATE(date) >= DATE('now','-7 days')")

    # Amount greater than
    match = re.search(r'greater than (\d+)', text)
    if match:
        amount = match.group(1)
        conditions.append(f"amount > {amount}")

    return conditions

def generate_sql(user_input):

    if not is_safe(user_input):
        return "❌ Dangerous SQL detected. Query blocked!"

    table = get_table_name(user_input)

    if not table:
        return "⚠️ Could not detect table."

    conditions = extract_conditions(user_input)

    query = f"SELECT * FROM {table}"

    if conditions:
        query += " WHERE " + " AND ".join(conditions)

    query += " LIMIT 10;"

    return query

def export_pdf(query):
    filename = f"SQL_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("<b>SQL Query Generator Report</b>", styles["Title"]))
    elements.append(Spacer(1, 0.5 * inch))

    elements.append(Paragraph(f"<b>Generated Query:</b>", styles["Heading2"]))
    elements.append(Spacer(1, 0.2 * inch))
    elements.append(Paragraph(query, styles["Normal"]))

    doc.build(elements)

    return filename

def process_input(user_input):
    sql = generate_sql(user_input)
    return sql

with gr.Blocks() as demo:

    gr.Markdown("# 💡 SQL Query Generator (Natural Language to SQL)")

    user_input = gr.Textbox(label="Enter your request")
    output = gr.Textbox(label="Generated SQL Query")

    generate_btn = gr.Button("Generate SQL")

    generate_btn.click(process_input, inputs=user_input, outputs=output)

demo.launch(share=True)